spring:
  profiles.active: default
---
spring:
  profiles: default

  application:
    name: TestApp

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:camunda;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
    jmx-enabled: true

camunda:

server:
  port: 9090

#logging.level.org.camunda.bpm: DEBUG
#logging.level.org.glassfish.jersey: DEBUG
